version: "3"

services:

  tesseract:
    image: tesseract:latest
    container_name: tesseract
    volumes:
      - ./resource/tesseract:/opt/tesseract/
      - ./resource/langdata:/tmp/langdata/
    tty: true
    environment:
      TZ: "Asia/Tokyo"